# Generated by Django 5.0.2 on 2024-02-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=50)),
                ('subject', models.CharField(default='No Subject', max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('attachment', models.FileField(default=0, upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status_reciever', models.CharField(default='unread', max_length=20)),
                ('status_sender', models.CharField(default='unread', max_length=20)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.register_tb')),
            ],
        ),
    ]
