# Generated by Django 5.0.2 on 2024-02-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_message_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_tb',
            name='recipient_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message_tb',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.register_tb'),
        ),
    ]
