# Generated by Django 5.0.2 on 2024-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_message_tb_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_tb',
            name='status_sender',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
