# Generated by Django 5.0.2 on 2024-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_message_tb_status_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_tb',
            name='attachment',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
