# Generated by Django 5.0.2 on 2024-02-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_block_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block_Tb',
        ),
    ]
