# Generated by Django 5.0.2 on 2024-02-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_delete_block_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_Tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=20)),
                ('blocked_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_app.register_tb')),
            ],
        ),
    ]
